In [88]:
import pandas as pd
from sklearn.cluster import KMeans
from sklearn.preprocessing import OneHotEncoder

In [89]:
df=pd.read_csv("student_performance.csv")
df.head()

,student_id,weekly_self_study_hours,attendance_percentage,class_participation,total_score,grade
0,1,18.5,95.6,3.8,97.9,A
1,2,14.0,80.0,2.5,83.9,B
2,3,19.5,86.3,5.3,100.0,A
3,4,25.7,70.2,7.0,100.0,A
4,5,13.4,81.9,6.9,92.0,A

In [90]:
encoder=OneHotEncoder(sparse_output=False)
df['grade']=encoder.fit_transform(df[['grade']])

In [91]:
df.head()

,student_id,weekly_self_study_hours,attendance_percentage,class_participation,total_score,grade
0,1,18.5,95.6,3.8,97.9,1.0
1,2,14.0,80.0,2.5,83.9,0.0
2,3,19.5,86.3,5.3,100.0,1.0
3,4,25.7,70.2,7.0,100.0,1.0
4,5,13.4,81.9,6.9,92.0,1.0

In [92]:
df.drop(columns='student_id',inplace=True)
model=KMeans(n_clusters=3,random_state=0)
# 3 clusters for best,avg abd poor
model.fit(df)
result=model.labels_
df['cluster_performance']=result
df

,weekly_self_study_hours,attendance_percentage,class_participation,total_score,grade,cluster_performance
0,18.5,95.6,3.8,97.9,1.0,2
1,14.0,80.0,2.5,83.9,0.0,1
2,19.5,86.3,5.3,100.0,1.0,2
3,25.7,70.2,7.0,100.0,1.0,2
4,13.4,81.9,6.9,92.0,1.0,2
...,...,...,...,...,...,...
999995,18.0,95.5,4.8,100.0,1.0,2
999996,15.7,82.7,6.7,88.3,1.0,1
999997,14.2,85.1,5.8,87.9,1.0,1
999998,25.3,90.0,5.3,100.0,1.0,2
999999,18.3,84.6,4.1,100.0,1.0,2

In [94]:
print(df['cluster_performance'].value_counts())
# here we can see our dataset divided into 3 categories

cluster_performance
2    464514
1    347947
0    187539
Name: count, dtype: int64

In [ ]:
cluster0_data = df[df['cluster_performance'] == 0]

print(cluster0_data)
#Seing only particular clustered data

        weekly_self_study_hours  attendance_percentage  class_participation  \
10                         11.8                   82.3                  4.6
13                          1.6                   92.1                  5.7
14                          2.9                   90.7                  5.4
16                          7.9                   85.9                  7.7
19                          5.1                   91.4                  4.5
...                         ...                    ...                  ...
999960                      7.2                   89.8                  6.8
999969                      9.4                   98.5                  3.9
999977                     11.6                   91.6                  8.3
999978                      6.3                   72.9                  4.5
999979                      7.3                   68.9                  6.9

        total_score  grade  cluster_performance
10             66.4    0.0                    0
13             60.9    0.0                    0
14             52.1    0.0                    0
16             63.0    0.0                    0
19             57.9    0.0                    0
...             ...    ...                  ...
999960         65.6    0.0                    0
999969         68.1    0.0                    0
999977         64.3    0.0                    0
999978         55.2    0.0                    0
999979         68.8    0.0                    0

[187539 rows x 6 columns]